name: Databricks CI/CD Deployment

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  development_deploy:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: https://${{ secrets.DEV_DEPLOY_URL }}
      DATABRICKS_TOKEN: ${{ secrets.DEV_DEPLOY_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install Databricks CLI
        run: databricks/setup-cli@main

      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.x'

      # - name: Install Databricks CLI
      #   run: pip install databricks-cli

      - name: Extract Branch Name
        id: extract_branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Update Databricks Dev Repo
        run: |
          databricks repos update --path /Repos/dev_workspace_path/your_repo --branch ${{ steps.extract_branch.outputs.branch }}

  production_deploy:
    needs: development_deploy
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: https://${{ secrets.PROD_DEPLOY_URL }}
      DATABRICKS_TOKEN: ${{ secrets.PROD_DEPLOY_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Databricks CLI
        run: databricks/setup-cli@main

      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.x'

      # - name: Install Databricks CLI
      #   run: pip install databricks-cli

      - name: Extract Branch Name
        id: extract_branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Update Databricks Prod Repo
        run: |
          databricks repos update --path /Repos/prod_workspace_path/your_repo --branch ${{ steps.extract_branch.outputs.branch }}
